syntax on
syntax enable
set background=dark
set number
set mouse=a
filetype plugin indent on

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif

autocmd vimenter * ++nested colorscheme gruvbox
